remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Sapphire
description: Shows upload & download speed below the status bar. Supports opa334’s TrollStore.
show_downloads: true
